#!/bin/bash
#
# DeepSea integration test "suites/basic/stage-5.sh"
#
# This script runs DeepSea stages 2 and 5 to remove a storage-only node from
# an existing Ceph cluster.
#
# In addition to the assumptions contained in qa/README, this script assumes
# that (1) DeepSea has already been used to deploy a cluster, (2) the
# cluster has at least one "storage-only" node (i.e. a node with role "storage"
# and no other roles (except possibly "admin")), and (3) the cluster will
# be able to reach HEALTH_OK without one storage-only node.
#
# On success (HEALTH_OK is reached), the script returns 0. On failure, for
# whatever reason, the script returns non-zero.
#
# The script produces verbose output on stdout, which can be captured for later
# forensic analysis.
#

set -e
set +x

SCRIPTNAME=$(basename ${0})
BASEDIR=$(readlink -f "$(dirname ${0})/../..")
test -d $BASEDIR
[[ $BASEDIR =~ \/qa$ ]]

source $BASEDIR/common/common.sh

function usage {
    set +x
    echo "$SCRIPTNAME - script for testing HEALTH_OK deployment"
    echo "for use in SUSE Enterprise Storage testing"
    echo
    echo "Usage:"
    echo "  $SCRIPTNAME [-h,--help] [--cli] [--client-nodes=X]"
    echo "  [--min-nodes=X] [--profile=X]"
    echo
    echo "Options:"
    echo "    --cli           Use DeepSea CLI"
    echo "    --client-nodes  Number of client (non-cluster) nodes"
    echo "    --help          Display this usage message"
    echo "    --min-nodes     Minimum number of nodes"
    echo "    --profile       Storage/OSD profile (see below)"
    echo
    echo "Supported storage/OSD profiles:"
    echo "    default         Whatever is generated by Stage 1 (bluestore)"
    echo "    dmcrypt         All encrypted OSDs"
    echo "    filestore       All filestore OSDs"
    echo "    random          A randomly chosen profile (teuthology/OVH only)"
    echo "    <OTHER>         Any other value will be assumed to be the name"
    echo "                    of an OSD profile in qa/osd-config/ovh"
    exit 1
}

assert_enhanced_getopt

TEMP=$(getopt -o h \
--long "cli,client-nodes:,help,mds,min-nodes:,profile:,rgw,ssl" \
-n 'health-ok.sh' -- "$@")

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around TEMP': they are essential!
eval set -- "$TEMP"

# process command-line options
CLI=""
CLIENT_NODES=0
STORAGE_PROFILE="default"
CUSTOM_STORAGE_PROFILE=""
MIN_NODES=1
while true ; do
    case "$1" in
        --cli) CLI="$1" ; shift ;;
        --client-nodes) shift ; CLIENT_NODES=$1 ; shift ;;
        -h|--help) usage ;;    # does not return
        --min-nodes) shift ; MIN_NODES=$1 ; shift ;;
        --profile) shift ; STORAGE_PROFILE=$1 ; shift ;;
        --) shift ; break ;;
        *) echo "Internal error" ; exit 1 ;;
    esac
done
echo "WWWW"
echo "stage-5.sh running with the following configuration:"
test -n "$CLI" && echo "- CLI"
echo "- CLIENT_NODES ->$CLIENT_NODES<-"
echo "- MIN_NODES ->$MIN_NODES<-"
echo "- PROFILE ->$STORAGE_PROFILE<-"

# prep and run stages
_initialize_storage_profile
_initialize_and_vet_nodes 
NODE_TO_DELETE=$(_first_storage_only_node)
echo "Preparing to remove storage node ->$NODE_TO_DELETE<-"
set -x
policy_remove_storage_node $NODE_TO_DELETE
run_stage_2 "$CLI"
ceph_cluster_status
run_stage_5 "$CLI"
ceph_cluster_status

# verification phase
ceph_health_test
salt -I roles:storage osd.report

echo "YYYY"
echo "stage-5 test result: PASS"
